on: [pull_request]

name: Run Tests

jobs:
  testing:
    name: testing-${{ matrix.toolchain }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
        # change to stable once #![feature(...)] is brought into stable rust
          - nightly
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
        
      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Run cargo test
        run: cargo nextest run --release --workspace --exclude faer-bench
